# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-13 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_dfmbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_message',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
